# Generated by Django 5.0.2 on 2024-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_fuel_user_nickname_user_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.CharField(
                blank=True, help_text="소개글", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="프로필 이미지",
                null=True,
                upload_to="profile_images/%Y/%m/%d/",
            ),
        ),
    ]
