# Generated by Django 5.0.2 on 2024-02-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_profile_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new",
            field=models.BooleanField(default=True, help_text="신규 회원"),
        ),
    ]
