# Generated by Django 4.2.10 on 2024-03-02 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_from",
                    models.ForeignKey(
                        help_text="발신자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_alarms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alarm_to",
                    models.ForeignKey(
                        help_text="수신자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_alarms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="목표",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="goals.goal",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="방",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
