<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-25 08:12

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 4.2.10 on 2024-03-02 04:26

>>>>>>> f6019b1b834cbce3ca20c372826d85452073abfa
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
        ('goals', '0003_alter_goal_belonging_group_id'),
        ('rooms', '0002_room_closing_date_room_deposit_room_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_from', models.ForeignKey(help_text='발신자', on_delete=django.db.models.deletion.CASCADE, related_name='sent_alarms', to=settings.AUTH_USER_MODEL)),
                ('alarm_to', models.ForeignKey(help_text='수신자', on_delete=django.db.models.deletion.CASCADE, related_name='received_alarms', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, help_text='목표', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goals.goal')),
                ('room', models.ForeignKey(blank=True, help_text='방', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='rooms.room')),
=======
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
>>>>>>> f6019b1b834cbce3ca20c372826d85452073abfa
            ],
        ),
    ]
