# Generated by Django 4.2.10 on 2024-03-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alarms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="current_user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
