# Generated by Django 4.2.10 on 2024-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="방 이름", max_length=50)),
                ("detail", models.TextField(help_text="세부사항")),
                (
                    "cert_required",
                    models.BooleanField(
                        blank=True, default=False, help_text="인증 필수 여부"
                    ),
                ),
                (
                    "cert_detail",
                    models.TextField(blank=True, help_text="인증 상세", null=True),
                ),
                (
                    "penalty_value",
                    models.PositiveIntegerField(default=0, help_text="벌금"),
                ),
                (
                    "favor_offline",
                    models.BooleanField(default=False, help_text="대면활동 유무"),
                ),
                ("is_active", models.BooleanField(default=False, help_text="활성화 여부")),
                ("deposit", models.PositiveIntegerField(default=0, help_text="보증금")),
                ("duration", models.DurationField(default=None, help_text="방 수명")),
                (
                    "closing_date",
                    models.DateTimeField(default=None, help_text="종료 시점", null=True),
                ),
                (
                    "penalty_bank",
                    models.PositiveIntegerField(default=0, help_text="벌금의 합"),
                ),
                (
                    "activity_tags",
                    models.ManyToManyField(
                        default=None, help_text="활동 태그", to="goals.activitytag"
                    ),
                ),
            ],
        ),
    ]
