# Generated by Django 5.0.2 on 2024-02-16 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goals", "0003_alter_goal_belonging_group_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="방 이름", max_length=50)),
                ("detail", models.TextField(help_text="세부사항")),
                (
                    "cert_required",
                    models.BooleanField(default=False, help_text="인증 필수 여부"),
                ),
                ("cert_detail", models.TextField(help_text="인증 상세", null=True)),
                (
                    "penalty_value",
                    models.PositiveIntegerField(default=0, help_text="벌금"),
                ),
                (
                    "favor_offline",
                    models.BooleanField(default=False, help_text="대면활동 유무"),
                ),
                ("is_active", models.BooleanField(default=False, help_text="활성화 여부")),
                (
                    "activity_tags",
                    models.ManyToManyField(
                        default=None, help_text="활동 태그", to="goals.activitytag"
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        help_text="그룹장",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        default=None,
                        help_text="그룹원",
                        related_name="members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        default=None, help_text="태그", to="goals.tag"
                    ),
                ),
            ],
        ),
    ]
