# Generated by Django 5.0.2 on 2024-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="closing_date",
            field=models.DateTimeField(default=None, help_text="종료 시점"),
        ),
        migrations.AddField(
            model_name="room",
            name="deposit",
            field=models.PositiveIntegerField(default=0, help_text="보증금"),
        ),
        migrations.AddField(
            model_name="room",
            name="duration",
            field=models.DurationField(default=None, help_text="방 수명"),
        ),
        migrations.AddField(
            model_name="room",
            name="penalty_bank",
            field=models.PositiveIntegerField(default=0, help_text="벌금의 합"),
        ),
    ]
