# Generated by Django 4.2.10 on 2024-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="closing_date",
            field=models.DateTimeField(default=None, help_text="종료 시점", null=True),
        ),
    ]
