# Generated by Django 4.2.10 on 2024-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cert_required',
            field=models.BooleanField(blank=True, default=False, help_text='인증 필수 여부'),
        ),
    ]
