# Generated by Django 4.2.10 on 2024-03-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_cert_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cert_detail',
            field=models.TextField(blank=True, help_text='인증 상세', null=True),
        ),
    ]
