# Generated by Django 5.0.2 on 2024-02-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=10)),
                (
                    "parent_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goals.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="목표 제목", max_length=50)),
                ("content", models.TextField(help_text="목표 내용")),
                (
                    "favor_offline",
                    models.BooleanField(default=False, help_text="대면 희망 여부"),
                ),
                (
                    "is_in_group",
                    models.BooleanField(default=False, help_text="그룹 소속 여부"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, help_text="목표 완료 여부"),
                ),
                (
                    "belonging_group_id",
                    models.IntegerField(help_text="소속 그룹", null=True),
                ),
                (
                    "activityTags",
                    models.ManyToManyField(
                        default=None, help_text="활동 태그", to="goals.activitytag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="유저",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        default=None, help_text="목표 태그", to="goals.tag"
                    ),
                ),
            ],
        ),
    ]
