# Generated by Django 5.0.3 on 2024-03-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='달성보고 이미지', null=True, upload_to='achievement_reports/')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='목표 제목', max_length=50)),
                ('content', models.TextField(help_text='목표 내용')),
                ('favor_offline', models.BooleanField(default=False, help_text='대면 희망 여부')),
                ('is_in_group', models.BooleanField(default=False, help_text='그룹 소속 여부')),
                ('is_completed', models.BooleanField(default=False, help_text='목표 완료 여부')),
                ('belonging_group_id', models.IntegerField(help_text='소속된 그룹', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
            ],
        ),
    ]
