# Generated by Django 5.0.2 on 2024-02-15 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="activityTags",
            new_name="activity_tags",
        ),
    ]
