# Generated by Django 4.2.10 on 2024-03-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="achievementreport",
            name="goal",
            field=models.ForeignKey(
                help_text="목표",
                on_delete=django.db.models.deletion.CASCADE,
                to="goals.goal",
            ),
        ),
        migrations.AddField(
            model_name="achievementreport",
            name="reacted_dislike",
            field=models.ManyToManyField(
                default=None,
                help_text="싫어요",
                related_name="disliked_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="achievementreport",
            name="reacted_love",
            field=models.ManyToManyField(
                default=None,
                help_text="찜하기",
                related_name="loved_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="achievementreport",
            name="reacted_respectful",
            field=models.ManyToManyField(
                default=None,
                help_text="좋아요",
                related_name="respected_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
