# Generated by Django 4.2.10 on 2024-03-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
