# Generated by Django 5.0.2 on 2024-02-25 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_belonging_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='달성보고 이미지', null=True, upload_to='achievement_reports/')),
                ('goal', models.ForeignKey(help_text='목표', on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
                ('reacted_dislike', models.ManyToManyField(default=None, help_text='싫어요', related_name='disliked_reports', to=settings.AUTH_USER_MODEL)),
                ('reacted_love', models.ManyToManyField(default=None, help_text='찜하기', related_name='loved_reports', to=settings.AUTH_USER_MODEL)),
                ('reacted_respectful', models.ManyToManyField(default=None, help_text='좋아요', related_name='respected_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
