# Generated by Django 4.2.10 on 2024-03-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivityinfo",
            name="room",
            field=models.ForeignKey(
                help_text="방",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_infos",
                to="rooms.room",
            ),
        ),
    ]
