# Generated by Django 4.2.10 on 2024-03-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivityinfo",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_infos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="room",
            field=models.ForeignKey(
                help_text="방",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_room",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="participated",
            field=models.ManyToManyField(
                default=None, help_text="참가 유저", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="room",
            field=models.ForeignKey(
                help_text="방",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
