# Generated by Django 4.2.10 on 2024-03-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivityinfo",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_infos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                help_text="작성자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="room",
            field=models.ForeignKey(
                help_text="방",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_posts",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="voter",
            field=models.ManyToManyField(
                help_text="추천인", related_name="voter_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="room",
            field=models.ForeignKey(
                help_text="방",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_room",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="memberauthentication",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="작성자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                help_text="게시물",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="activities.post",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="voter",
            field=models.ManyToManyField(
                help_text="추천인",
                related_name="voter_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="participated",
            field=models.ManyToManyField(
                default=None, help_text="참가 유저", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="room",
            field=models.ForeignKey(
                help_text="방",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="user",
            field=models.ForeignKey(
                help_text="유저",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
